### PR TITLE
Add BluePower ore generation support

### PR DESCRIPTION
**Pull request by FantasyTeddy**
My first commit (6a7d923) is an attempt to introduce a new distribution function in order to simplify most of the ore generation registration.
Usually ore generation is done with four variables:
- **veinCount**: the amount of veins per chunk
- **veinSize**: the amount of blocks per vein
- **minY**: the lowest Y value for a vein
- **maxY**: the highest Y value for a vein

With the new function, those values can be passed directly and there is no additional calculation required.

The second commit (c8dad12) adds BluePower support for its ore generation (as suggested in Issue #46).

### CODE REVIEW

**Comment by way2muchnoise** [comment]
@FantasyTeddy Looks good, can't do anything wrong with adding more things

**Comment by FantasyTeddy** [comment]
Great, thanks for merging!

Btw, is there something that can be done for Jenkins to build successfully again?

**Comment by way2muchnoise** [comment]
Nope nothing you can do @jakimfett needs to do that

**Comment by FantasyTeddy** [comment]
Okay :smiley:

**Comment by jakimfett** [comment]
@FantasyTeddy @way2muchnoise I've been too busy the last couple of days to address the Jenkins build issues. I'll (hopefully) have time to fix it tomorrow or the next day.

**Comment by FantasyTeddy** [comment]
@jakimfett There's no hurry. I was just wondering if I could help somehow.

**Pull request merged**
