### PR TITLE
Add compatibility for Reliquary mob drops

### PR DESCRIPTION
**Pull request by FantasyTeddy**
I hope I did everything as it should be done...!

### CODE REVIEW

**Comment by FantasyTeddy** [comment]
Can someone tell me, why the Jenkins build failed?

**Comment by hilburn** [comment]
Jenkins isn't successfully adding reliquary as a lib

**Comment by FantasyTeddy** [comment]
Ah okay, so it wasn't my fault then?

**Comment by hilburn** [comment]
well if you tested it and it worked before pushing, then probs not

**Comment by way2muchnoise** [comment]
@FantasyTeddy It isn't your fault I successfully build it locally it is just Jenkins derping.

**Comment by FantasyTeddy** [comment]
Yes I did test it. Just scared me a little that Jenkins was complaining^^

**Pull request merged**
